//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrmocIMSEntities : DbContext
    {
        public OrmocIMSEntities()
            : base("name=OrmocIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CodeDetail> CodeDetails { get; set; }
        public virtual DbSet<ItemDetail> ItemDetails { get; set; }
        public virtual DbSet<ItemDetailMapping> ItemDetailMappings { get; set; }
        public virtual DbSet<ItemRequestForm> ItemRequestForms { get; set; }
        public virtual DbSet<ItemRequestFormMapping> ItemRequestFormMappings { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<PurchaseOrderMapping> PurchaseOrderMappings { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationsMapping> QuotationsMappings { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagsMapping> TagsMappings { get; set; }
        public virtual DbSet<UnitsOfMeasure> UnitsOfMeasures { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
