//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMSRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrmocIMSEntities : DbContext
    {
        public OrmocIMSEntities()
            : base("name=OrmocIMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CodeDetail> CodeDetails { get; set; }
        public virtual DbSet<ItemDetail> ItemDetails { get; set; }
        public virtual DbSet<ItemDetailMapping> ItemDetailMappings { get; set; }
        public virtual DbSet<ItemRequestForm> ItemRequestForms { get; set; }
        public virtual DbSet<ItemRequestFormMapping> ItemRequestFormMappings { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<PurchaseOrderMapping> PurchaseOrderMappings { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<Quotation> Quotations { get; set; }
        public virtual DbSet<QuotationsMapping> QuotationsMappings { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagsMapping> TagsMappings { get; set; }
        public virtual DbSet<UnitsOfMeasure> UnitsOfMeasures { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<AdvancedSearch_SP_Result> AdvancedSearch_SP(string moduleNm, string param1, string param2, string param3, string param4, string param5, string param6, string param7, string param8, string param9)
        {
            var moduleNmParameter = moduleNm != null ?
                new ObjectParameter("ModuleNm", moduleNm) :
                new ObjectParameter("ModuleNm", typeof(string));
    
            var param1Parameter = param1 != null ?
                new ObjectParameter("param1", param1) :
                new ObjectParameter("param1", typeof(string));
    
            var param2Parameter = param2 != null ?
                new ObjectParameter("param2", param2) :
                new ObjectParameter("param2", typeof(string));
    
            var param3Parameter = param3 != null ?
                new ObjectParameter("param3", param3) :
                new ObjectParameter("param3", typeof(string));
    
            var param4Parameter = param4 != null ?
                new ObjectParameter("param4", param4) :
                new ObjectParameter("param4", typeof(string));
    
            var param5Parameter = param5 != null ?
                new ObjectParameter("param5", param5) :
                new ObjectParameter("param5", typeof(string));
    
            var param6Parameter = param6 != null ?
                new ObjectParameter("param6", param6) :
                new ObjectParameter("param6", typeof(string));
    
            var param7Parameter = param7 != null ?
                new ObjectParameter("param7", param7) :
                new ObjectParameter("param7", typeof(string));
    
            var param8Parameter = param8 != null ?
                new ObjectParameter("param8", param8) :
                new ObjectParameter("param8", typeof(string));
    
            var param9Parameter = param9 != null ?
                new ObjectParameter("param9", param9) :
                new ObjectParameter("param9", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdvancedSearch_SP_Result>("AdvancedSearch_SP", moduleNmParameter, param1Parameter, param2Parameter, param3Parameter, param4Parameter, param5Parameter, param6Parameter, param7Parameter, param8Parameter, param9Parameter);
        }
    }
}
